-- ============================================================
-- MIGRATION v1.11.0 — SIDE FUND (petty-cash-style shared pool)
--
-- Adds an optional "side fund": a shared pool for normal day-to-day
-- simple activities that members contribute a monthly due into. It
-- is NOT a separate bank account — it is an "envelope" balance
-- layered inside an existing Primary or Secondary account
-- (side_fund_config.parent_account_id), which is why activating it
-- requires picking that parent account (and therefore its currency).
--
-- Every side fund contribution or expense is dual-posted, in the
-- same DB transaction, so the two numbers can never drift apart:
--   1. A completely normal transaction on the parent account — so
--      the account's real balance is always correct, and expenses
--      show up in the ordinary Transactions ledger exactly like any
--      other expense ("recorded as general expenses" per spec)
--   2. An increment/decrement of side_fund_config.current_balance
--      (the envelope) by the exact same amount
--
-- Each member owes a monthly due (side_fund_config.monthly_amount,
-- changeable at any time — a change only affects dues generated from
-- that point on). Dues are auto-generated for every active
-- shareholder on the 1st of each month by a new cron job; any due
-- still unpaid when the following month's job runs is marked
-- DEFAULTED (see jobs/scheduler.js).
--
-- New tables: side_fund_config (singleton), side_fund_dues,
--             side_fund_expenses
-- Altered tables: transactions (new inflow_type SIDE_FUND_CONTRIBUTION_IN)
-- New permissions: SIDE_FUND_VIEW, SIDE_FUND_MANAGE,
--             SIDE_FUND_CONTRIBUTION_RECORD, SIDE_FUND_EXPENSE_RECORD
--
-- Safe to run more than once — every statement checks first.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 1. Side fund settings (singleton, id=1) — starts inactive with
--    no parent account/currency until an Admin/Treasurer activates
--    it from Settings.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS side_fund_config (
    id                 INTEGER       PRIMARY KEY DEFAULT 1,
    is_active          BOOLEAN       NOT NULL DEFAULT FALSE,
    parent_account_id  INTEGER REFERENCES accounts(id),
    currency_id        INTEGER REFERENCES currencies(id),
    monthly_amount     NUMERIC(20,4) NOT NULL DEFAULT 0,
    current_balance    NUMERIC(20,4) NOT NULL DEFAULT 0,
    updated_by         INTEGER REFERENCES users(id),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT single_side_fund_row         CHECK (id = 1),
    CONSTRAINT non_negative_side_fund_balance CHECK (current_balance >= 0),
    CONSTRAINT non_negative_monthly_amount    CHECK (monthly_amount >= 0)
);

INSERT INTO side_fund_config (id, is_active, monthly_amount, current_balance)
VALUES (1, FALSE, 0, 0)
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- 2. One row per member per calendar month (period = 'YYYY-MM'),
--    auto-generated by the monthly cron job. Recording a payment
--    against a due is what actually moves the money.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS side_fund_dues (
    id             SERIAL PRIMARY KEY,
    user_id        INTEGER       NOT NULL REFERENCES users(id),
    period         CHAR(7)       NOT NULL,
    amount_due     NUMERIC(20,4) NOT NULL,
    amount_paid    NUMERIC(20,4) NOT NULL DEFAULT 0,
    status         VARCHAR(20)   NOT NULL DEFAULT 'PENDING'
                   CHECK (status IN ('PENDING','PARTIAL','PAID','DEFAULTED')),
    transaction_id INTEGER REFERENCES transactions(id),
    paid_date      DATE,
    recorded_by    INTEGER REFERENCES users(id),
    notes          TEXT,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT non_negative_side_fund_due  CHECK (amount_due >= 0),
    CONSTRAINT non_negative_side_fund_paid CHECK (amount_paid >= 0),
    UNIQUE (user_id, period)
);

-- ------------------------------------------------------------
-- 3. Expenses drawn from the side fund envelope — the underlying
--    money movement is a completely normal EXPENSE transaction
--    against the parent account; this table links that transaction
--    back to the side fund so its envelope balance can be decremented.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS side_fund_expenses (
    id             SERIAL PRIMARY KEY,
    reference_id   INTEGER       NOT NULL REFERENCES references_registry(id),
    transaction_id INTEGER       NOT NULL REFERENCES transactions(id),
    amount         NUMERIC(20,4) NOT NULL,
    description    TEXT          NOT NULL,
    expense_date   DATE          NOT NULL,
    recorded_by    INTEGER       NOT NULL REFERENCES users(id),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT positive_side_fund_expense CHECK (amount > 0)
);

-- ------------------------------------------------------------
-- 4. Transactions: dedicated inflow_type value for side fund
--    contributions, so they're traceable in reports instead of
--    hiding under the generic OTHER_INCOME bucket. (Side fund
--    expenses deliberately reuse the plain 'EXPENSE' inflow_type —
--    no change needed there, per "recorded as general expenses".)
-- ------------------------------------------------------------
DO $$
DECLARE
    con_name text;
BEGIN
    SELECT conname INTO con_name
    FROM   pg_constraint
    WHERE  conrelid = 'transactions'::regclass
    AND    contype = 'c'
    AND    pg_get_constraintdef(oid) LIKE '%inflow_type%CONTRIBUTION%';
    IF con_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE transactions DROP CONSTRAINT %I', con_name);
    END IF;
END $$;

ALTER TABLE transactions ADD CONSTRAINT transactions_inflow_type_check
    CHECK (inflow_type IN (
        'CONTRIBUTION', 'GRANT', 'LOAN_RECEIVED', 'LOAN_REPAYMENT_IN',
        'INTEREST_IN', 'INVESTMENT_RETURN', 'TRANSFER_IN', 'OTHER_INCOME',
        'SAVINGS_DEPOSIT_IN', 'TRANSFER_OUT', 'LOAN_DISBURSED',
        'LOAN_REPAYMENT_OUT', 'INTEREST_OUT', 'EXPENSE',
        'SAVINGS_HANDOUT_OUT', 'GRANT_REFUND', 'SIDE_FUND_CONTRIBUTION_IN'
    ));

-- ------------------------------------------------------------
-- 5. Indexes
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_side_fund_dues_user   ON side_fund_dues (user_id);
CREATE INDEX IF NOT EXISTS idx_side_fund_dues_period ON side_fund_dues (period);
CREATE INDEX IF NOT EXISTS idx_side_fund_dues_status ON side_fund_dues (status);

-- ------------------------------------------------------------
-- 6. New permissions
-- ------------------------------------------------------------
INSERT INTO permissions (code, module, description) VALUES
    ('SIDE_FUND_VIEW',                'FINANCE', 'View side fund balance, dues, and spending history'),
    ('SIDE_FUND_MANAGE',              'FINANCE', 'Activate/deactivate the side fund and change its settings'),
    ('SIDE_FUND_CONTRIBUTION_RECORD', 'FINANCE', 'Record a member''s monthly side fund due as paid'),
    ('SIDE_FUND_EXPENSE_RECORD',      'FINANCE', 'Record an expense drawn from the side fund')
ON CONFLICT (code) DO NOTHING;

COMMIT;

-- ------------------------------------------------------------
-- After running this migration:
--   1. Restart the backend and rebuild/refresh the frontend so it
--      picks up the code changes deployed alongside this migration.
--   2. Go to Settings > Roles & Permissions and grant the four new
--      SIDE_FUND_* permissions to the right roles — suggested:
--        - SIDE_FUND_VIEW                -> Treasurer, Assistant Treasurer, Director
--        - SIDE_FUND_MANAGE              -> Admin, Treasurer
--        - SIDE_FUND_CONTRIBUTION_RECORD -> Treasurer, Assistant Treasurer
--        - SIDE_FUND_EXPENSE_RECORD      -> Treasurer, Assistant Treasurer
--      Nothing works for anyone until these are granted — permissions
--      are never auto-assigned by a migration.
--   3. The side fund starts INACTIVE. Go to the new Side Fund page
--      (or Settings, if you added a panel there) and activate it:
--      choose the parent Primary/Secondary account it will live
--      inside (this also fixes its currency) and set the monthly
--      per-member due amount. Until you do this, no dues are
--      generated and no side fund actions are available.
--   4. Once active, dues are auto-generated for every active
--      shareholder on the 1st of each month at the configured
--      monthly_amount. A due still unpaid when the following month's
--      job runs is automatically marked DEFAULTED — it does not
--      block anything, it's just a record that it wasn't paid.
--   5. If cms_user doesn't already have full rights on changed tables
--      via an admin/pgAdmin connection, re-run:
--        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cms_user;
--        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO cms_user;
-- ------------------------------------------------------------
